### ISSUE TITLE
Crashing on iphone 5s

### ISSUE THREAD

**Issue by matthewjdrover** [larcus94/ImagePickerSheet#17]
It works great in the simulator but when ran on my phone it crashes. I'm running ios 8.1.1 on a 5s. To be sure it was not my implementation, I used your code sample to test.

**Comment by larcus94** [comment]
You need to give me a crash log so that I can help you

**Comment by larcus94** [comment]
@matthewjdrover Do you have any info for me?

**Comment by matthewjdrover** [comment]
Running your example on my iphone starts fine. I press to activate the picker. I 'Allow' access to my photos. then crash.

xcode says "Terminated due to Memory error"

and the output log shows "2015-05-22 10:00:05.735 BRNImagePickerSheet[667:179775] Connection to assetsd was interrupted or assetsd died". This message only came up the first time I ran it. The memory error comes up every time.

That's very little to go on I know. Just to note, I have 2000 images on my phone currently. Not sure if it's relevant.

**Comment by larcus94** [comment]
@matthewjdrover That's weird, it certainly doesn't load 2000 images in memory. Do you have a stack trace or something else?

**Comment by larcus94** [comment]
@matthewjdrover Oh, are you running the latest commit btw?

**Comment by matthewjdrover** [comment]
This is what I get from the latest. My phone is running 8.1.1 btw.

dyld: Library not loaded: @rpath/ImagePickerSheet.framework/ImagePickerSheet
  Referenced from: /private/var/mobile/Containers/Bundle/Application/7FF567A0-A881-41D9-8CDB-2E99A5311AF6/Example.app/Example
  Reason: image not found
(lldb)

**Comment by larcus94** [comment]
Pull and try again please :)

**Comment by matthewjdrover** [comment]
Works great. Thanks.

**Comment by matthewjdrover** [comment]
The example works fine, but when I include your project into mine I get this error again. Only on my phone, the simulator works fine.

It says image not found, so I copied your asset images into my assets, but still no go. 

dyld: Library not loaded: @rpath/ImagePickerSheetController.framework/ImagePickerSheetController
  Referenced from: /private/var/mobile/Containers/Bundle/Application/DDF8141B-20E7-4B02-8F54-DC74363C061A/myapp.app/myapp
  Reason: image not found

**Comment by matthewjdrover** [comment]
Never mind. I forgot to set the imbedded binaries. This is some great code. Thanks.

**Comment by larcus94** [comment]
@matthewjdrover perfect, thanks a lot :)
