### ISSUE TITLE
Error using member 'selectedPhotos' in a story board app

### ISSUE THREAD

**Issue by gluecode** [larcus94/ImagePickerSheet#19]
ImagePickerSheet in a story board app produces an error when using the member **selectedPhotos** for ImagePickerSheet.

The error reported is: 
**'ImagePickerSheet' does not have a member named 'selectedPhotos'**

I've created a test story board app here: https://github.com/gluecode/ImagePickerSheetStoryBoard

![screen shot 2015-05-22 at 10 06 23 am](https://cloud.githubusercontent.com/assets/15410/7775713/4b750cdc-006a-11e5-8d2c-f4f3051f492a.png)

**Comment by larcus94** [comment]
`selectedPhotos` is a instance variable that I removed some time ago. However, I forgot to update the README. I did so now. Use `numberOfSelectedPhotos` instead.
